spring:
  application:
    name: growing-pots
  profiles:
    default: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    try-it-out-enabled: true