spring:
  application:
    name: growing-pots
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    max-http-form-post-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    try-it-out-enabled: true

oauth:
  kakao:
    user-info-uri: https://kapi.kakao.com/v2/user/me

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${spring.profiles.active}
  send-default-pii: false